import Head from "next/head";
import { Inter } from "@next/font/google";
import { LoginBtn } from "./components/login-btn";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Personal-Trainer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={inter.className}>Personal-Trainer</h1>
      <LoginBtn />
    </>
  );
}
